---
abstract: "use the \"abook\" program as the addex source"
author:
  - 'Ricardo SIGNES, C<< <rjbs@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.88'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: App::Addex::AddressBook::Abook
name: App-Addex-AddressBook-Abook
no_index:
  directory:
    - inc
    - t
requires:
  App::Addex: 0.007
  Config::INI::Reader: 0.011
  File::HomeDir: 0
  File::Spec: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rjbs/app-addex-addressbook-abook
version: 0.006
